export const FETCH_DEPARTMENTS_PENDING = "FETCH_DEPARTMENTS_PENDING";
export const FETCH_DEPARTMENTS_SUCCESS = "FETCH_DEPARTMENTS_SUCCESS";
export const FETCH_DEPARTMENTS_ERROR = "FETCH_DEPARTMENTS_ERROR";