export const FETCH_STAFFS_PENDING = "FETCH_STAFFS_PENDING";
export const FETCH_STAFFS_SUCCESS = "FETCH_STAFFS_SUCCESS";
export const FETCH_STAFFS_ERROR = "FETCH_STAFFS_ERROR";
export const DELETED_STAFF = "DELETED_STAFF";
export const EDIT_STAFF = "EDIT_STAFF";